import type { LocalizedText } from "@/lib/i18n-content"

export interface StaffMember {
    name: LocalizedText
    age: number | null
    height: number | null
    weight: number | null
    bust: string
    photos: string[]
    hasVideo?: boolean
}

export const STAFF: StaffMember[] = [
    { name: { ru: "Вера", en: "Vera", zh: "薇拉" }, age: 23, height: 177, weight: 58, bust: "2", photos: ["/specilists/vera/vera.jpg.avif", "/specilists/vera/vera_2-2.jpg.avif", "/specilists/vera/vera_3-2.jpg.avif", "/specilists/vera/vera_4-3.jpg.avif", "/specilists/vera/vera_5-3.jpg.avif"] },
    { name: { ru: "Анабель", en: "Anabel", zh: "安娜贝尔" }, age: 25, height: 170, weight: 54, bust: "3,5", photos: ["/specilists/anabel/anabel.jpg.avif", "/specilists/anabel/anabel_2.jpg.avif", "/specilists/anabel/anabel_3.jpg.avif", "/specilists/anabel/anabel_4.jpg.avif", "/specilists/anabel/anabel_5.jpg.avif", "/specilists/anabel/anabel_6.jpg.avif", "/specilists/anabel/anabel_7.jpg.avif", "/specilists/anabel/anabel_8.jpg.avif", "/specilists/anabel/anabel_9.jpg.avif", "/specilists/anabel/anabel_10.jpg.avif", "/specilists/anabel/anabel_11.jpg.avif", "/specilists/anabel/anabel_12.jpg.avif", "/specilists/anabel/anabel_13.jpg.avif"] },
    { name: { ru: "Шакира", en: "Shakira", zh: "夏奇拉" }, age: 29, height: 175, weight: 68, bust: "4", photos: ["/specilists/shakira/shakira.jpg.avif", "/specilists/shakira/shakira_2-2.jpg.avif", "/specilists/shakira/shakira_3-1.jpg.avif", "/specilists/shakira/shakira_4-2.jpg.avif", "/specilists/shakira/shakira_5-2.jpg.avif", "/specilists/shakira/shakira_6-2.jpg.avif", "/specilists/shakira/shakira_7-1.jpg.avif"] },
    { name: { ru: "Злата", en: "Zlata", zh: "兹拉塔" }, age: 27, height: 170, weight: 53, bust: "3 (sil)", photos: ["/specilists/zlata/zlata.jpg.avif", "/specilists/zlata/zlata_2-2.jpg.avif", "/specilists/zlata/zlata_3-2.jpg.avif", "/specilists/zlata/zlata_4-2.jpg.avif", "/specilists/zlata/zlata_5.jpg.avif"] },
    { name: { ru: "Трейси", en: "Tracey", zh: "特蕾西" }, age: 23, height: 171, weight: 60, bust: "2", photos: ["/specilists/traysi/tracey_1-1.jpg.avif", "/specilists/traysi/tracey_2-1.jpg.avif", "/specilists/traysi/tracey_3-1.jpg.avif", "/specilists/traysi/tracey_4-1.jpg.avif", "/specilists/traysi/tracey_5-1.jpg.avif", "/specilists/traysi/tracey_6-1.jpg.avif"] },
    { name: { ru: "Элина", en: "Elina", zh: "埃琳娜" }, age: 25, height: 160, weight: 60, bust: "4", photos: ["/specilists/elina/elina.jpg.avif", "/specilists/elina/elina_2.jpg.avif", "/specilists/elina/elina_3.jpg.avif"] },
    { name: { ru: "Снежана", en: "Snezhana", zh: "斯涅扎娜" }, age: 29, height: 160, weight: 51, bust: "1,5", photos: ["/specilists/snejana/snezhana-1.jpg.avif", "/specilists/snejana/snezhana_2-1.jpg.avif", "/specilists/snejana/snezhana_3-1.jpg.avif", "/specilists/snejana/snezhana_4-1.jpg.avif"] },
    { name: { ru: "Нелли", en: "Nellie", zh: "内莉" }, age: 24, height: 165, weight: 55, bust: "4 (sil)", photos: ["/specilists/nelli/nellie_1.jpg.avif", "/specilists/nelli/nellie_2.jpg.avif", "/specilists/nelli/nellie_3.jpg.avif", "/specilists/nelli/nellie_4.jpg.avif"] },
    { name: { ru: "Андреа", en: "Andrea", zh: "安德莉亚" }, age: 28, height: 175, weight: 65, bust: "3 (sil)", photos: ["/specilists/andrea/andrea.jpg.avif", "/specilists/andrea/andrea_2.jpg.avif", "/specilists/andrea/andrea_3.jpg.avif", "/specilists/andrea/andrea_4.jpg.avif"] },
    { name: { ru: "Юля", en: "Julia", zh: "尤利娅" }, age: 20, height: 165, weight: 50, bust: "1,5", photos: ["/specilists/yulya/julia_1-1.jpg.avif", "/specilists/yulya/julia_2-1.jpg.avif", "/specilists/yulya/julia_3-1.jpg.avif", "/specilists/yulya/julia_4-1.jpg.avif", "/specilists/yulya/julia_5.jpg.avif", "/specilists/yulya/julia_6.jpg.avif", "/specilists/yulya/julia_7.jpg.avif", "/specilists/yulya/julia_8.jpg.avif"] },
    { name: { ru: "Долорес", en: "Dolores", zh: "多洛雷斯" }, age: 19, height: 163, weight: 51, bust: "2", photos: ["/specilists/dolores/dolores.jpg.avif", "/specilists/dolores/dolores_2-1.jpg.avif", "/specilists/dolores/dolores_3-1.jpg.avif", "/specilists/dolores/dolores_4-1.jpg.avif"] },
    { name: { ru: "Арина", en: "Arina", zh: "阿丽娜" }, age: 19, height: 165, weight: 50, bust: "2,5", photos: ["/specilists/arina/arina_2.jpg.avif", "/specilists/arina/arina_3.jpg.avif", "/specilists/arina/arina_5.jpg.avif", "/specilists/arina/arina_6.jpg.avif"] },
    { name: { ru: "Арсения", en: "Arseniya", zh: "阿尔谢尼娅" }, age: 27, height: 175, weight: 50, bust: "4", photos: ["/specilists/arseniya/britney.jpg.avif", "/specilists/arseniya/britney_2.jpg.avif", "/specilists/arseniya/britney_3.jpg.avif"] },
    { name: { ru: "Шейла", en: "Sheila", zh: "希拉" }, age: 44, height: 162, weight: 54, bust: "3 (sil)", photos: ["/specilists/shayla/sheila_1.jpg.avif", "/specilists/shayla/sheila_2.jpg.avif", "/specilists/shayla/sheila_3.jpg.avif", "/specilists/shayla/sheila_4.jpg.avif", "/specilists/shayla/sheila_5.jpg.avif", "/specilists/shayla/sheila_6.jpg.avif"] },
    { name: { ru: "Божена", en: "Bozhena", zh: "博热娜" }, age: 31, height: 170, weight: 52, bust: "2", photos: ["/specilists/bojena/img_6599.jpg.avif", "/specilists/bojena/img_6600.jpg.avif", "/specilists/bojena/img_9690.jpeg.avif", "/specilists/bojena/img_9691.jpeg.avif", "/specilists/bojena/img_9695.jpeg.avif", "/specilists/bojena/img_9696.jpeg.avif", "/specilists/bojena/img_9698.jpeg.avif", "/specilists/bojena/img_9701.jpeg.avif", "/specilists/bojena/img_9703.jpeg.avif"] },
    { name: { ru: "Оля", en: "Olya", zh: "奥莉娅" }, age: 24, height: 160, weight: 56, bust: "2", photos: ["/specilists/olya/olya.jpg.avif", "/specilists/olya/olya_2.jpg.avif", "/specilists/olya/olya_3.jpg.avif"] },
    { name: { ru: "Лара", en: "Lara", zh: "拉拉" }, age: 25, height: 164, weight: 68, bust: "2,5", photos: ["/specilists/lara/lara.jpg.avif", "/specilists/lara/lara_2.jpg.avif", "/specilists/lara/lara_3.jpg.avif", "/specilists/lara/lara_4.jpg.avif", "/specilists/lara/lara_5.jpg.avif", "/specilists/lara/lara_6.jpg.avif", "/specilists/lara/lara_7.jpg.avif"] },
    { name: { ru: "Арья", en: "Arya", zh: "阿莉娅" }, age: 20, height: 162, weight: 56, bust: "2", photos: ["/specilists/arya/arya.jpg.avif", "/specilists/arya/arya_3.jpg.avif"] },
    { name: { ru: "Джиджи", en: "Gigi", zh: "吉吉" }, age: 20, height: 175, weight: 54, bust: "1,5", photos: ["/specilists/dzhidzhi/gigi.jpg.avif", "/specilists/dzhidzhi/gigi_2.jpg.avif", "/specilists/dzhidzhi/gigi_3.jpg.avif", "/specilists/dzhidzhi/gigi_4.jpg.avif"] },
    { name: { ru: "Микаса", en: "Mikasa", zh: "米卡萨" }, age: 27, height: 173, weight: 60, bust: "2", photos: ["/specilists/mikasa/wil.jpg.avif", "/specilists/mikasa/wil_2.jpg.avif", "/specilists/mikasa/wil_3.jpg.avif"] },
    { name: { ru: "Линда", en: "Linda", zh: "琳达" }, age: 27, height: 163, weight: 51, bust: "2", photos: ["/specilists/linda/linda.jpg.avif", "/specilists/linda/linda_2.jpg.avif", "/specilists/linda/linda_3.jpg.avif", "/specilists/linda/linda_4.jpg.avif", "/specilists/linda/linda_5.jpg.avif"] },
    { name: { ru: "Белла", en: "Bella", zh: "贝拉" }, age: 22, height: 164, weight: 47, bust: "2,5", photos: ["/specilists/bella/bella.jpg.avif", "/specilists/bella/bella_2.jpg.avif", "/specilists/bella/bella_3.jpg.avif", "/specilists/bella/bella_4.jpg.avif", "/specilists/bella/bella_5.jpg.avif", "/specilists/bella/bella_6.jpg.avif", "/specilists/bella/bella_7.jpg.avif", "/specilists/bella/bella_8.jpg.avif", "/specilists/bella/bella_9.jpg.avif", "/specilists/bella/bella_10.jpg.avif"] },
    { name: { ru: "Нана", en: "Nana", zh: "娜娜" }, age: 23, height: 164, weight: 52, bust: "3,5 (sil)", photos: ["/specilists/nana/nana_1.jpg.avif", "/specilists/nana/nana_2.jpg.avif", "/specilists/nana/nana_3.jpg.avif", "/specilists/nana/nana_4.jpg.avif", "/specilists/nana/nana_5.jpg.avif", "/specilists/nana/nana_6.jpg.avif", "/specilists/nana/nana_7.jpg.avif", "/specilists/nana/nana_8.jpg.avif", "/specilists/nana/nana_9.jpg.avif", "/specilists/nana/nana_10.jpg.avif", "/specilists/nana/nana_11.jpg.avif"] },
    { name: { ru: "Лия", en: "Lia", zh: "莉娅" }, age: 20, height: 162, weight: 48, bust: "1,5", photos: ["/specilists/leah/lia-01.jpg.avif", "/specilists/leah/lia-02.jpg.avif", "/specilists/leah/lia-03.jpg.avif", "/specilists/leah/lia-04.jpg.avif", "/specilists/leah/lia-05.jpg.avif"] },
    { name: { ru: "Жасмин", en: "Jasmine", zh: "茉莉" }, age: 33, height: 167, weight: 55, bust: "3", photos: ["/specilists/jasmin/janine.jpg.avif", "/specilists/jasmin/janine_2.jpg.avif", "/specilists/jasmin/janine_3.jpg.avif", "/specilists/jasmin/janine_4.jpg.avif"] },
    { name: { ru: "Слава", en: "Slava", zh: "斯拉瓦" }, age: 19, height: 173, weight: 62, bust: "1,5", photos: ["/specilists/slava/photo_2024-02-22_23-06-51.jpg.avif", "/specilists/slava/photo_2024-02-22_23-06-54.jpg.avif", "/specilists/slava/photo_2024-02-22_23-06-55-2.jpg.avif", "/specilists/slava/photo_2024-02-22_23-06-55.jpg.avif", "/specilists/slava/photo_2024-02-22_23-06-56.jpg.avif"] },
    { name: { ru: "Элис", en: "Alice", zh: "爱丽丝" }, age: 20, height: 162, weight: 50, bust: "1,5", photos: ["/specilists/elis/tvaila_1.jpg.avif", "/specilists/elis/tvaila_2.jpg.avif", "/specilists/elis/tvaila_3.jpg.avif", "/specilists/elis/tvaila_4.jpg.avif", "/specilists/elis/tvaila_5.jpg.avif"] },
    { name: { ru: "Амина", en: "Amina", zh: "阿米娜" }, age: 22, height: 172, weight: 58, bust: "2", photos: ["/specilists/amina/amina_1.jpg.avif", "/specilists/amina/amina_2.jpg.avif", "/specilists/amina/amina_3.jpg.avif", "/specilists/amina/amina_4.jpg.avif", "/specilists/amina/amina_5.jpg.avif", "/specilists/amina/amina_6.jpg.avif", "/specilists/amina/amina_7.jpg.avif", "/specilists/amina/amina_8.jpg.avif"] },
    { name: { ru: "Малина", en: "Malina", zh: "玛琳娜" }, age: 20, height: 170, weight: 55, bust: "1,5", photos: ["/specilists/malina/malina.jpg.avif", "/specilists/malina/malina_2.jpg.avif"] },
    { name: { ru: "Лиза", en: "Liza", zh: "丽扎" }, age: 23, height: 152, weight: 43, bust: "2", photos: ["/specilists/liza/liza.jpg.avif", "/specilists/liza/liza_2.jpg.avif", "/specilists/liza/liza_3.jpg.avif", "/specilists/liza/liza_4.jpg.avif", "/specilists/liza/liza_5.jpg.avif", "/specilists/liza/liza_6.jpg.avif", "/specilists/liza/liza_7.jpg.avif", "/specilists/liza/liza_8.jpg.avif", "/specilists/liza/liza_9.jpg.avif", "/specilists/liza/liza_10.jpg.avif"] },
    { name: { ru: "Эля", en: "Elya", zh: "艾莉娅" }, age: 27, height: 167, weight: 50, bust: "2", photos: ["/specilists/elya/elya_1.jpg.avif", "/specilists/elya/elya_2.jpg.avif", "/specilists/elya/elya_3.jpg.avif", "/specilists/elya/elya_4.jpg.avif", "/specilists/elya/elya_5.jpg.avif", "/specilists/elya/elya_6.jpg.avif", "/specilists/elya/elya_7.jpg.avif", "/specilists/elya/elya_8.jpg.avif"] },
    { name: { ru: "Марго", en: "Margo", zh: "玛尔戈" }, age: 38, height: 168, weight: 59, bust: "3", photos: ["/specilists/margo/margo.jpg.avif", "/specilists/margo/margo_2.jpg.avif", "/specilists/margo/margo_3.jpg.avif", "/specilists/margo/margo_4.jpg.avif", "/specilists/margo/margo_5.jpg.avif", "/specilists/margo/margo_6.jpg.avif", "/specilists/margo/margo_7.jpg.avif", "/specilists/margo/margo_8.jpg.avif", "/specilists/margo/margo_9.jpg.avif"] },
    { name: { ru: "Дакота", en: "Dakota", zh: "达科塔" }, age: 25, height: 168, weight: 65, bust: "1,5", photos: ["/specilists/dakota/dakota.jpg.avif", "/specilists/dakota/dakota_2.jpg.avif", "/specilists/dakota/dakota_3.jpg.avif"] },
    { name: { ru: "Марлен", en: "Marlene", zh: "玛琳" }, age: 26, height: 179, weight: 56, bust: "2", photos: ["/specilists/marlen/marlene.jpg.avif", "/specilists/marlen/marlene_2.jpg.avif", "/specilists/marlen/marlene_3.jpg.avif", "/specilists/marlen/marlene_4.jpg.avif"] },
    { name: { ru: "Лея", en: "Leia", zh: "蕾雅" }, age: 18, height: 153, weight: 50, bust: "2,5", photos: ["/specilists/leya/leia_6-1.jpg.avif", "/specilists/leya/leia_7-1.jpg.avif", "/specilists/leya/leia_8-1.jpg.avif", "/specilists/leya/leia_9-1.jpg.avif", "/specilists/leya/leia_10-1.jpg.avif", "/specilists/leya/leia_11-1.jpg.avif", "/specilists/leya/leia_12-1.jpg.avif", "/specilists/leya/leia_13-1.jpg.avif", "/specilists/leya/leia_14-1.jpg.avif"] },
    { name: { ru: "Санни", en: "Sunny", zh: "桑妮" }, age: 22, height: 173, weight: 63, bust: "1,5", photos: ["/specilists/sunny/1-3.jpg.avif", "/specilists/sunny/2-3.jpg.avif", "/specilists/sunny/3-4.jpg.avif", "/specilists/sunny/4-3.jpg.avif", "/specilists/sunny/5-2.jpg.avif", "/specilists/sunny/6-1.jpg.avif", "/specilists/sunny/7-1.jpg.avif", "/specilists/sunny/8-1.jpg.avif"] },
    { name: { ru: "Шерил", en: "Sheryl", zh: "谢丽尔" }, age: 19, height: 164, weight: 48, bust: "1,5", photos: ["/specilists/sharil/sheryl_1.jpg.avif", "/specilists/sharil/sheryl_2.jpg.avif", "/specilists/sharil/sheryl_3.jpg.avif", "/specilists/sharil/sheryl_4.jpg.avif", "/specilists/sharil/sheryl_5.jpg.avif"] },
    { name: { ru: "Инга", en: "Inga", zh: "英加" }, age: 24, height: 162, weight: 51, bust: "1,5", photos: ["/specilists/inga/inga_1.jpg.avif", "/specilists/inga/inga_2.jpg.avif", "/specilists/inga/inga_3.jpg.avif", "/specilists/inga/inga_4.jpg.avif", "/specilists/inga/inga_5.jpg.avif"] },
    { name: { ru: "Монталь", en: "Montal", zh: "蒙塔尔" }, age: 26, height: 158, weight: 44, bust: "2,5", photos: ["/specilists/montal/montal-1.jpg.avif", "/specilists/montal/montal-2.jpg.avif", "/specilists/montal/montal-3.jpg.avif", "/specilists/montal/montal-4.jpg.avif", "/specilists/montal/montal-5.jpg.avif"] },
    { name: { ru: "Дейзи", en: "Daisy", zh: "黛西" }, age: 23, height: 169, weight: 60, bust: "3", photos: ["/specilists/daisy/daisy.jpg.avif", "/specilists/daisy/daisy_2.jpg.avif", "/specilists/daisy/daisy_3.jpg.avif", "/specilists/daisy/daisy_4.jpg.avif"] },
    { name: { ru: "Дарина", en: "Darina", zh: "达丽娜" }, age: 24, height: 160, weight: 44, bust: "2", photos: ["/specilists/darina/darina_2.jpg.avif", "/specilists/darina/darkina_1.jpg.avif"] },
    { name: { ru: "Эффи", en: "Effie", zh: "艾菲" }, age: 22, height: 171, weight: 53, bust: "1,5", photos: ["/specilists/effi/effie_1.jpg.avif", "/specilists/effi/effie_2.jpg.avif", "/specilists/effi/effie_3.jpg.avif", "/specilists/effi/effie_6.jpg.avif"] },
    { name: { ru: "Самер", en: "Samer", zh: "萨梅尔" }, age: 19, height: 156, weight: 47, bust: "2", photos: ["/specilists/samer/1-1.jpg.avif", "/specilists/samer/2-1.jpg.avif", "/specilists/samer/3-1.jpg.avif", "/specilists/samer/4.jpg.avif", "/specilists/samer/5.jpg.avif", "/specilists/samer/6.jpg.avif"] },
    { name: { ru: "Августина", en: "Augustina", zh: "奥古斯蒂娜" }, age: 22, height: 155, weight: 45, bust: "2", photos: ["/specilists/avgustina/augustina_1-1.jpg.avif", "/specilists/avgustina/augustina_2-1.jpg.avif", "/specilists/avgustina/augustina_3-1.jpg.avif", "/specilists/avgustina/augustina_4-1.jpg.avif", "/specilists/avgustina/augustina_5-1.jpg.avif", "/specilists/avgustina/augustina_6-1.jpg.avif"] },
    { name: { ru: "Мейзи", en: "Maisie", zh: "梅茜" }, age: 24, height: 177, weight: 61, bust: "4 (sil)", photos: ["/specilists/mayzi/maisie_2.jpg.avif", "/specilists/mayzi/maisie_4.jpg.avif", "/specilists/mayzi/maisie_5.jpg.avif", "/specilists/mayzi/maisie_6.jpg.avif", "/specilists/mayzi/maisie_7.jpg.avif", "/specilists/mayzi/maisie_8.jpg.avif"] },
    { name: { ru: "Тори", en: "Torie", zh: "托丽" }, age: 27, height: 160, weight: 48, bust: "2,5 (sil)", photos: ["/specilists/torie/torie_1.jpg.avif", "/specilists/torie/torie_2.jpg.avif", "/specilists/torie/torie_3.jpg.avif", "/specilists/torie/torie_4.jpg.avif"] },
    { name: { ru: "Астра", en: "Astra", zh: "阿斯特拉" }, age: 18, height: 168, weight: 40, bust: "1,5", photos: ["/specilists/astra/iness_1-1.jpg.avif", "/specilists/astra/iness_2-1.jpg.avif", "/specilists/astra/iness_3-1.jpg.avif", "/specilists/astra/iness_4-1.jpg.avif", "/specilists/astra/iness_5-1.jpg.avif"] },
    { name: { ru: "Адель", en: "Adelle", zh: "阿黛尔" }, age: 25, height: 170, weight: 57, bust: "2,5", photos: ["/specilists/adelle/adelle_1.jpg.avif", "/specilists/adelle/adelle_2.jpg.avif", "/specilists/adelle/adelle_3.jpg.avif", "/specilists/adelle/adelle_4.jpg.avif", "/specilists/adelle/adelle_5.jpg.avif", "/specilists/adelle/adelle_6.jpg.avif", "/specilists/adelle/adelle_7.jpg.avif", "/specilists/adelle/adelle_8.jpg.avif", "/specilists/adelle/adelle_9.jpg.avif"] },
    { name: { ru: "Глория", en: "Gloria", zh: "格洛丽亚" }, age: 18, height: 158, weight: 50, bust: "2", photos: ["/specilists/gloriya/gloria-1.jpg.avif", "/specilists/gloriya/gloria-2.jpg.avif", "/specilists/gloriya/gloria-3.jpg.avif", "/specilists/gloriya/gloria-4.jpg.avif", "/specilists/gloriya/gloria-5.jpg.avif", "/specilists/gloriya/gloria-6.jpg.avif", "/specilists/gloriya/gloria-7.jpg.avif", "/specilists/gloriya/gloria-8.jpg.avif", "/specilists/gloriya/gloria-9.jpg.avif"] },
    { name: { ru: "Есения", en: "Esenia", zh: "叶塞尼娅" }, age: null, height: null, weight: null, bust: "1,5", photos: ["/specilists/esenia/esenia0001.png.avif", "/specilists/esenia/esenia0002.png.avif", "/specilists/esenia/esenia0003.png.avif", "/specilists/esenia/esenia0004.png.avif"] },
];
